#!/bin/bash

# Test Notification System APIs

echo "🔔 Testing Notification System APIs..."
echo ""

# Check if dev server is running
echo "1️⃣ Checking if dev server is running..."
if curl -s http://localhost:3000/login > /dev/null 2>&1; then
    echo "✅ Dev server is running"
else
    echo "❌ Dev server is not running. Please start it with: bun run dev"
    exit 1
fi
echo ""

# This script requires manual testing through the UI
echo "📋 Manual Testing Steps:"
echo ""
echo "1. Open the app in your browser (Preview Panel)"
echo "2. Login with your phone number"
echo "3. Scroll down to 'ابزارهای توسعه' section"
echo "4. In 'تست نوتیفیکیشن‌ها' section, click on each notification type:"
echo "   - یادآوری تعهد روزانه"
echo "   - یادآوری بازتاب"
echo "   - تکمیل برنامه"
echo "   - گزارش هفتگی"
echo "   - موفقیت جدید"
echo "   - پیشرفت برنامه"
echo ""
echo "5. For each notification, verify:"
echo "   ✅ Notification is created (success message appears)"
echo "   ✅ Bell icon shows the unread count badge"
echo "   ✅ Click bell to open dropdown"
echo "   ✅ Notification appears in the list"
echo "   ✅ Unread notification has blue background"
echo "   ✅ Time is displayed correctly"
echo "   ✅ Action button (if any) works"
echo "   ✅ Mark as read button works"
echo "   ✅ Delete button works"
echo "   ✅ Badge count updates correctly"
echo ""
echo "6. Test 'Mark all as read' button:"
echo "   ✅ Click 'همه خوانده شد' button"
echo "   ✅ All notifications become read"
echo "   ✅ Badge disappears (count = 0)"
echo "   ✅ Blue background is removed"
echo ""
echo "7. Test refresh on dropdown open:"
echo "   ✅ Close dropdown"
echo "   ✅ Create new notification"
echo "   ✅ Open dropdown again"
echo "   ✅ New notification appears without page refresh"
echo ""
echo "8. Test action links:"
echo "   ✅ Click on action button in notification"
echo "   ✅ Navigate to correct page"
echo "   ✅ Notification is marked as read"
echo ""
echo "🎯 API Endpoints Tested:"
echo "   - GET    /api/notifications"
echo "   - POST   /api/notifications"
echo "   - PATCH  /api/notifications/[id]"
echo "   - DELETE /api/notifications/[id]"
echo "   - POST   /api/notifications/mark-read"
echo "   - POST   /api/dev/create-test-notification"
echo ""
echo "✨ Test completed! Check for any errors in browser console."
